# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
orbs:
  browser-tools: circleci/browser-tools@1.1
jobs:
  build:
    docker:
      - image: cimg/php:7.4.14-browsers

    steps:
      - checkout

      - run: cp .env.example .env
      - run: mv .env.testing .env

      # Download and cache dependencies

      # composer cache
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: 
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: Generate key
          command: php artisan key:generate
      # rn tests with phpunit or codecept
      - run: ./vendor/bin/phpunit tests/Unit